### ISSUE TITLE
Gradle compiler returns 0 exit code for some errors

### ISSUE THREAD

**Issue by raiju** [palantir/conjure#678]
## What happened?

When trying to compile a conjure definition with gradle-conjure, no files were generated. Digging deeper, no new IR files were being generated. Executing the compile command directly resulted in the following output:

```
java.lang.RuntimeException: Encountered error trying to parse file '<FILE>'
	at com.palantir.conjure.defs.ConjureParserUtils.lambda$parseConjureDef$3(ConjureParserUtils.java:228)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
	at com.palantir.conjure.defs.ConjureParserUtils.parseConjureDef(ConjureParserUtils.java:199)
	at com.palantir.conjure.defs.Conjure.parse(Conjure.java:37)
	at com.palantir.conjure.cli.ConjureCli$CompileCommand.generate(ConjureCli.java:91)
	at com.palantir.conjure.cli.ConjureCli$CompileCommand.run(ConjureCli.java:85)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1919)
	at picocli.CommandLine.access$1100(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
	at picocli.CommandLine.execute(CommandLine.java:2058)
	at com.palantir.conjure.cli.ConjureCli.main(ConjureCli.java:46)
Caused by: java.lang.NullPointerException: Import not found for namespace: Namespace{name=<NAMESPACE_NAME>}
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:987)
	at com.palantir.conjure.defs.ConjureTypeParserVisitor$ByParsedRepresentationTypeNameResolver.resolve(ConjureTypeParserVisitor.java:66)
	at com.palantir.conjure.defs.ConjureTypeParserVisitor.visitForeignReference(ConjureTypeParserVisitor.java:143)
	at com.palantir.conjure.defs.ConjureTypeParserVisitor.visitForeignReference(ConjureTypeParserVisitor.java:41)
	at com.palantir.conjure.parser.types.reference.ForeignReferenceType.visit(ForeignReferenceType.java:33)
	at com.palantir.conjure.defs.ConjureParserUtils.parseArgs(ConjureParserUtils.java:412)
	at com.palantir.conjure.defs.ConjureParserUtils.parseEndpoint(ConjureParserUtils.java:365)
	at com.palantir.conjure.defs.ConjureParserUtils.lambda$parseService$5(ConjureParserUtils.java:266)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1521)
	at com.palantir.conjure.defs.ConjureParserUtils.parseService(ConjureParserUtils.java:266)
	at com.palantir.conjure.defs.ConjureParserUtils.lambda$parseConjureDef$2(ConjureParserUtils.java:217)
	at java.base/java.util.LinkedHashMap.forEach(LinkedHashMap.java:723)
	at java.base/java.util.Collections$UnmodifiableMap.forEach(Collections.java:1521)
	at com.palantir.conjure.defs.ConjureParserUtils.lambda$parseConjureDef$3(ConjureParserUtils.java:216)
	... 13 more
```

with a 0 return code. This meant that the next build steps were executed.

## What did you want to happen?

A non-zero return code, which would then enable `GradleExecUtils` to print out the error.

**Comment by ferozco** [comment]
This was an issue with conjure CLI which was fixed here: https://github.com/palantir/conjure/pull/675. An upgrade should sort you out
